##########
# Blocks #
##########
stone:
  sync:
    position: true
    rotation: true
  entities:
    display_1:
      type: BLOCK_DISPLAY
      block: STONE
      interpolation-duration: 3
      teleport-duration: 3
grass:
  sync:
    position: true
    rotation: true
  entities:
    display_1:
      type: BLOCK_DISPLAY
      block: GRASS_BLOCK
      interpolation-duration: 2
      teleport-duration: 2
tnt:
  sync:
    position: true
    rotation: true
  entities:
    display_1:
      type: BLOCK_DISPLAY
      block: TNT
      interpolation-duration: 1
      teleport-duration: 1
slab:
  sync:
    position: true
    rotation: true
  entities:
    display_1:
      type: BLOCK_DISPLAY
      block: OAK_SLAB
      interpolation-duration: 1
      teleport-duration: 1

########
# Test #
########
test_light_cube:
  sync:
    position: true
    rotation: true
  entities:
    display:
      type: BLOCK_DISPLAY
      block: WHITE_CONCRETE
      scale: "1.0 1.0 1.0"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1

test_heavy_cube:
  sync:
    position: true
    rotation: true
  entities:
    display:
      type: BLOCK_DISPLAY
      block: OBSIDIAN
      scale: "1.0 1.0 1.0"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1

test_slippery_puck:
  sync:
    position: true
    rotation: true
  entities:
    core:
      type: BLOCK_DISPLAY
      block: PACKED_ICE
      # Approximation of cylinder(radius=0.45, height=0.2)
      scale: "0.9 0.2 0.9"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1
    rim_x_pos:
      type: BLOCK_DISPLAY
      block: PACKED_ICE
      scale: "0.2 0.2 0.6"
      translation: "0.25 0.0 0.0"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1
    rim_x_neg:
      type: BLOCK_DISPLAY
      block: PACKED_ICE
      scale: "0.2 0.2 0.6"
      translation: "-0.25 0.0 0.0"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1
    rim_z_pos:
      type: BLOCK_DISPLAY
      block: PACKED_ICE
      scale: "0.6 0.2 0.2"
      translation: "0.0 0.0 0.25"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1
    rim_z_neg:
      type: BLOCK_DISPLAY
      block: PACKED_ICE
      scale: "0.6 0.2 0.2"
      translation: "0.0 0.0 -0.25"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1

test_bouncy_ball:
  sync:
    position: true
    rotation: true
  entities:
    # Approximation of sphere(radius=0.4) by small cubes
    c:
      type: BLOCK_DISPLAY
      block: SLIME_BLOCK
      scale: "0.35 0.35 0.35"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1
    x_pos:
      type: BLOCK_DISPLAY
      block: SLIME_BLOCK
      scale: "0.25 0.25 0.25"
      translation: "0.23 0.0 0.0"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1
    x_neg:
      type: BLOCK_DISPLAY
      block: SLIME_BLOCK
      scale: "0.25 0.25 0.25"
      translation: "-0.23 0.0 0.0"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1
    y_pos:
      type: BLOCK_DISPLAY
      block: SLIME_BLOCK
      scale: "0.25 0.25 0.25"
      translation: "0.0 0.23 0.0"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1
    y_neg:
      type: BLOCK_DISPLAY
      block: SLIME_BLOCK
      scale: "0.25 0.25 0.25"
      translation: "0.0 -0.23 0.0"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1
    z_pos:
      type: BLOCK_DISPLAY
      block: SLIME_BLOCK
      scale: "0.25 0.25 0.25"
      translation: "0.0 0.0 0.23"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1
    z_neg:
      type: BLOCK_DISPLAY
      block: SLIME_BLOCK
      scale: "0.25 0.25 0.25"
      translation: "0.0 0.0 -0.23"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1

test_capsule:
  sync:
    position: true
    rotation: true
  entities:
    # Approximation of capsule(height=1.6, radius=0.25):
    # middle cylinder + 2 "sphere" caps.
    mid:
      type: BLOCK_DISPLAY
      block: SMOOTH_QUARTZ
      scale: "0.5 1.6 0.5"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1
    cap_top_c:
      type: BLOCK_DISPLAY
      block: SMOOTH_QUARTZ
      scale: "0.28 0.28 0.28"
      translation: "0.0 0.8 0.0"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1
    cap_top_x_pos:
      type: BLOCK_DISPLAY
      block: SMOOTH_QUARTZ
      scale: "0.20 0.20 0.20"
      translation: "0.14 0.8 0.0"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1
    cap_top_x_neg:
      type: BLOCK_DISPLAY
      block: SMOOTH_QUARTZ
      scale: "0.20 0.20 0.20"
      translation: "-0.14 0.8 0.0"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1
    cap_top_z_pos:
      type: BLOCK_DISPLAY
      block: SMOOTH_QUARTZ
      scale: "0.20 0.20 0.20"
      translation: "0.0 0.8 0.14"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1
    cap_top_z_neg:
      type: BLOCK_DISPLAY
      block: SMOOTH_QUARTZ
      scale: "0.20 0.20 0.20"
      translation: "0.0 0.8 -0.14"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1
    cap_bot_c:
      type: BLOCK_DISPLAY
      block: SMOOTH_QUARTZ
      scale: "0.28 0.28 0.28"
      translation: "0.0 -0.8 0.0"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1
    cap_bot_x_pos:
      type: BLOCK_DISPLAY
      block: SMOOTH_QUARTZ
      scale: "0.20 0.20 0.20"
      translation: "0.14 -0.8 0.0"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1
    cap_bot_x_neg:
      type: BLOCK_DISPLAY
      block: SMOOTH_QUARTZ
      scale: "0.20 0.20 0.20"
      translation: "-0.14 -0.8 0.0"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1
    cap_bot_z_pos:
      type: BLOCK_DISPLAY
      block: SMOOTH_QUARTZ
      scale: "0.20 0.20 0.20"
      translation: "0.0 -0.8 0.14"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1
    cap_bot_z_neg:
      type: BLOCK_DISPLAY
      block: SMOOTH_QUARTZ
      scale: "0.20 0.20 0.20"
      translation: "0.0 -0.8 -0.14"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1

test_compound_hammer:
  sync:
    position: true
    rotation: true
  entities:
    handle:
      type: BLOCK_DISPLAY
      block: OAK_LOG
      scale: "0.16 0.9 0.16"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1
    head:
      type: BLOCK_DISPLAY
      block: IRON_BLOCK
      scale: "0.64 0.2 0.24"
      translation: "0.0 0.5 0.0"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1

test_static_wall:
  sync:
    position: true
    rotation: true
  entities:
    wall:
      type: BLOCK_DISPLAY
      block: STONE
      scale: "1.0 2.0 0.3"
      rotate-translation: true
      interpolation-duration: 1
      teleport-duration: 1

##########
# Chains #
##########
iron_chain:
  sync:
    position: true
    rotation: true
  entities:
    display_1:
      type: ITEM_DISPLAY
      item-model: items.iron_chain  # ItemStack-конфіг
      display-mode: NONE
      scale: "1.15 1.15 1.15"
      show-when:
        active: true
        sleeping: true
      interpolation-duration: 1
      teleport-duration: 1

############
# Ragdolls #
############
ragdoll_head:
  entities:
    display:
      type: ITEM_DISPLAY
      display-mode: THIRDPERSON_RIGHTHAND
      local-offset: "0.0 0.0 0.0"
      translation: "0.0 0.0 0.0"
      item-model: items.ragdoll_head
      rotate-translation: false
      interpolation-duration: 1
      teleport-duration: 1
ragdoll_right_arm:
  entities:
    display:
      type: ITEM_DISPLAY
      display-mode: THIRDPERSON_RIGHTHAND
      local-offset: "0.05 0.35 -0.05"
      translation: "0.0 -1024 0.0"
      item-model: items.ragdoll_right_arm
      rotate-translation: false
      interpolation-duration: 1
      teleport-duration: 1
ragdoll_left_arm:
  entities:
    display:
      type: ITEM_DISPLAY
      display-mode: THIRDPERSON_RIGHTHAND
      local-offset: "0.0 0.35 0.05"
      translation: "0.0 -2048 0.0"
      item-model: items.ragdoll_left_arm
      rotate-translation: false
      interpolation-duration: 1
      teleport-duration: 1
ragdoll_torso:
  entities:
    display:
      type: ITEM_DISPLAY
      display-mode: THIRDPERSON_RIGHTHAND
      local-offset: "0.0 0.6 0.0"
      translation: "0.0 -5120 0.0"
      item-model: items.ragdoll_torso
      rotate-translation: false
      interpolation-duration: 1
      teleport-duration: 1
ragdoll_right_leg:
  entities:
    display:
      type: ITEM_DISPLAY
      display-mode: THIRDPERSON_RIGHTHAND
      local-offset: "0.0 0.435 0.0"
      translation: "0.0 -6144 0.0"
      item-model: items.ragdoll_right_leg
      rotate-translation: false
      interpolation-duration: 1
      teleport-duration: 1
ragdoll_left_leg:
  entities:
    display:
      type: ITEM_DISPLAY
      display-mode: THIRDPERSON_RIGHTHAND
      local-offset: "0.0 0.435 0.0"
      translation: "0.0 -7168 0.0"
      item-model: items.ragdoll_left_leg
      rotate-translation: false
      interpolation-duration: 1
      teleport-duration: 1


####################
# FORMAT FILE
#example:
#  sync:
#    position: true
#    rotation: true
#  entities:
#    example_armorstand:
#      type: ARMOR_STAND
#      item-model: items:example      # ключ items.yml з ItemStack’ами
#      small: false
#      invisible: true
#      marker: true
#      base-plate: false
#      arms: false
#      local-offset: "0.0 0.0 0.0"
#      local-rotation: "0.0 0.0 0.0" # pitch, yaw, roll
#      show-when:
#        active: true
#        sleeping: true
#    example2:
#      type: ARMOR_STAND
#      item-model: items:example2
#      small: true
#      invisible: true
#      marker: true
#      local-offset: "0.0 0.8 0.0"
#      local-rotation: "0.0 0.0 0.0"
#      show-when:
#        active: true
#        sleeping: false
#    example3:
#      type: ITEM_DISPLAY
#      item-model: items:example3
#      display-mode: HEAD             # FIRSTPERSON_LEFTHAND/FIRSTPERSON_RIGHTHAND/FIXED/GROUND/GUI/HEAD/NONE/THIRDPERSON_LEFTHAND/THIRDPERSON_RIGHTHAND
#      local-offset: "0.0 0.0 0.0"
#      local-rotation: "0.0 0.0 0.0"
#      scale: "1.0 1.0 1.0"
#      view-range: 128
#      shadow-radius: 4
#      shadow-strength: 0
#      interpolation-duration: 3
#      teleport-duration: 3
#      billboard: FIXED
#      brightness:
#        block: 15
#        sky: 15
#      show-when:
#        active: true
#        sleeping: true
#    example4:
#      type: BLOCK_DISPLAY
#      block: STONE
#      local-offset: "0.0 -0.5 0.0"
#      local-rotation: "0.0 0.0 0.0"
#      scale: "1.0 1.0 1.0"
#      view-range: 128
#      shadow-radius: 4
#      shadow-strength: 0
#      interpolation-duration: 3
#      teleport-duration: 3
#      billboard: FIXED
#      brightness:
#        block: 15
#        sky: 15
#      show-when:
#        active: true
#        sleeping: true
